# Generated by Django 4.1 on 2022-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="last_name",
        ),
        migrations.AddField(
            model_name="student",
            name="gpa",
            field=models.CharField(
                choices=[
                    ("F", "Fail"),
                    ("D", "Critical"),
                    ("C", "Good"),
                    ("B", "Great"),
                    ("A", "Excellent"),
                ],
                default="F",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="joined_date",
            field=models.DateField(auto_now=True),
        ),
    ]
