# Generated by Django 4.1 on 2022-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0002_remove_student_first_name_remove_student_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="is_engaged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="gpa",
            field=models.CharField(
                choices=[
                    ("A", "Excellent"),
                    ("B", "Great"),
                    ("C", "Good"),
                    ("D", "Critical"),
                    ("F", "Fail"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
