# Generated by Django 4.1 on 2022-08-20 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_lesson_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="finish_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
